### ISSUE TITLE
Key for rpmfusion-nonfree-fedora-29 does not match !

### ISSUE THREAD

**Issue by otopetrik** [sourcejedi/ansible-rpmfusion__impl#1]
Thanks for very useful rpmfusion ansible roles.  Unfortunately on Fedora 29, the instalation of rpmfusion-nonfree fails.
(rpmfusion-free role succeeded)

ansible run:
```
TASK [sourcejedi.rpmfusion__impl : Verify rpmfusion release RPM] ******************************************************
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|failed` use `result is failed`.
This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
fatal: [fedora29.lan]: FAILED! => {"changed": false, "cmd": ["rpm", "--checksig", "rpmfusion-nonfree-release-29.noarch.rpm"], "delta": "0:00:00.027855", "end": "2018-11-09 19:51:27.493229", "msg": "non-zero return code", "rc": 1, "start": "2018-11-09 19:51:27.465374", "stderr": "", "stderr_lines": [], "stdout": "rpmfusion-nonfree-release-29.noarch.rpm: digests SIGNATURES NOT OK", "stdout_lines": ["rpmfusion-nonfree-release-29.noarch.rpm: digests SIGNATURES NOT OK"]}
```

running rpm directly
```
$ LC_ALL=C rpm -v --checksig /ansible-managed/rpmfusion/rpmfusion-nonfree-release-29.noarch.rpm
/ansible-managed/rpmfusion/rpmfusion-nonfree-release-29.noarch.rpm:
    Header V4 RSA/SHA1 Signature, key ID d6841af8: NOKEY
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    V4 RSA/SHA1 Signature, key ID d6841af8: NOKEY
    MD5 digest: OK
```

Looks like rpmfusion uses different key for non-free repository https://rpmfusion.org/keys#RPM_Fusion_nonfree_for_Fedora_29
(note the date 2018-04-03)

**Comment by sourcejedi** [comment]
Should work now. Glad I wrote a script for key updates. Thanks for the nice report :-).

It's good to hear from a user. I'm curious, did you like this role because it checks the key, or did you just want a convenient installer? Are you just using the role on one computer, or are you doing something a bit more more interesting?

**Comment by otopetrik** [comment]
Thanks for the fix, it works now.
(the wrong key can be removed using `rpm -e gpg-pubkey-8d10c0fd-5a09d7ce`)

Yes, verifying the rpm against the key stored in role itself is the main reason.
I also like the the fact, that it skips all the work, if the rpmfusion is already installed :)

Nothing interesting - just reinstalling few home machines (notebook, desktops) and making next reinstalls faster by moving the configuration to ansible.

**Comment by sourcejedi** [comment]
Great, thanks again :-).

I'm unlikely to remove any of the old keys, unless there was some information about a security breach.  https://unix.stackexchange.com/questions/400634/does-anyone-bother-to-remove-rpmkeys [answer: no].


(Technically I have a little bit of code around removing keys.  See also [rpmfusion-remove](https://github.com/sourcejedi/ansible-rpmfusion-remove/blob/255115f/tasks/main-tasks.yml#L76).  It's not pretty, it doesn't sound like you need it, and it would be a much bigger hammer than just removing the key.  FWIW I guess I tried to make the key removal work as securely as I could, [here](https://github.com/sourcejedi/ansible-rpmfusion__impl/blob/master/tasks/install-nonidempotent.yml#L46) :-).)
